import 'package:core_fit/features/market/market_home/data/item_types_model.dart';
import 'package:core_fit/features/market/market_home/data/market_model.dart';
import 'package:core_fit/features/market/market_home/data/product_model.dart';

List<String> testSwiperImages = [
  'assets/images/1.png',
  'assets/images/2.png',
  'assets/images/3.png',
];

List<ItemTypesModel> testItemTypes = [
  ItemTypesModel(
    title: 'Sports Shoes',
    image: 'assets/icons/shoce.svg',
  ),
  ItemTypesModel(
    title: 'Tennis',
    image: 'assets/icons/closes.svg',
  ),
  ItemTypesModel(
    title: 'Basketball',
    image: 'assets/icons/shoce.svg',
  ),
  ItemTypesModel(
    title: 'Tennis',
    image: 'assets/icons/closes.svg',
  ),
  ItemTypesModel(
    title: 'Eating',
    image: 'assets/icons/shoce.svg',
  ),
  ItemTypesModel(
    title: 'drinks',
    image: 'assets/icons/closes.svg',
  ),
  ItemTypesModel(
    title: 'Tennis',
    image: 'assets/icons/shoce.svg',
  ),
  ItemTypesModel(
    title: 'Tennis',
    image: 'assets/icons/closes.svg',
  ),
];

List<MarketModel> testMarket = [
  MarketModel(
    title: 'Nike Air Max 97',
    image: 'https://picsum.photos/id/83/200/300',
    subtitle: ' Nike Air Max 97',
    isClosed: true,
  ),
  MarketModel(
    title: 'Nike Air Max 97',
    image: 'https://picsum.photos/id/31/200/300',
    subtitle: ' Nike Air Max 97',
    isClosed: false,
  ),
  MarketModel(
    title: 'Nike Air Max 97',
    image: 'https://picsum.photos/id/75/200/300',
    subtitle: ' Nike Air Max 97',
    isClosed: true,
  ),
  MarketModel(
    title: 'Nike Air Max 97',
    image: 'https://picsum.photos/id/65/200/300',
    subtitle: ' Nike Air Max 97',
    isClosed: false,
  ),
  MarketModel(
    title: 'Nike Air Max 97',
    image: 'https://picsum.photos/id/17/200/300',
    subtitle: ' Nike Air Max 97',
    isClosed: true,
  ),
  MarketModel(
    title: 'Nike Air Max 97',
    image: 'https://picsum.photos/id/83/200/300',
    subtitle: ' Nike Air Max 97',
    isClosed: false,
  ),
  MarketModel(
    title: 'Nike Air Max 97',
    image: 'https://picsum.photos/id/76/200/300',
    subtitle: ' Nike Air Max 97',
    isClosed: true,
  ),
  MarketModel(
    title: 'Nike Air Max 97',
    image: 'https://picsum.photos/id/72/200/300',
    subtitle: ' Nike Air Max 97',
    isClosed: false,
  ),
  MarketModel(
    title: 'Nike Air Max 97',
    image: 'https://picsum.photos/id/33/200/300',
    subtitle: ' Nike Air Max 97',
    isClosed: true,
  ),
  MarketModel(
    title: 'Nike Air Max 97',
    image: 'https://picsum.photos/id/64/200/300',
    subtitle: ' Nike Air Max 97',
    isClosed: false,
  ),
  MarketModel(
    title: 'Nike Air Max 97',
    image: 'https://picsum.photos/id/85/200/300',
    subtitle: ' Nike Air Max 97',
    isClosed: true,
  ),
  MarketModel(
    title: 'Nike Air Max 97',
    image: 'https://picsum.photos/id/553/200/300',
    subtitle: ' Nike Air Max 97',
    isClosed: false,
  ),
  MarketModel(
    title: 'Nike Air Max 97',
    image: 'https://picsum.photos/id/35/200/300',
    subtitle: ' Nike Air Max 97',
    isClosed: true,
  ),
  MarketModel(
    title: 'Nike Air Max 97',
    image: 'https://picsum.photos/id/100/200/300',
    subtitle: ' Nike Air Max 97',
    isClosed: false,
  ),
  MarketModel(
    title: 'Nike Air Max 97',
    image: 'https://picsum.photos/id/11/200/300',
    subtitle: ' Nike Air Max 97',
    isClosed: true,
  ),
  MarketModel(
    title: 'Nike Air Max 97',
    image: 'https://picsum.photos/id/40/200/300',
    subtitle: ' Nike Air Max 97',
    isClosed: false,
  ),
  MarketModel(
    title: 'Nike Air Max 97',
    image: 'https://picsum.photos/id/60/200/300',
    subtitle: ' Nike Air Max 97',
    isClosed: true,
  ),
  MarketModel(
    title: 'Nike Air Max 97',
    image: 'https://picsum.photos/id/30/200/300',
    subtitle: ' Nike Air Max 97',
    isClosed: false,
  ),
];

List<ProductModel> testProducts = [
  ProductModel(
    title: 'Nike Air Max 97 Black White version fewee wgeeeewf fwfewfef wqfffffffffffffffff fwqefqwfqw fweqf  1',
    image: 'https://picsum.photos/id/46/200/300',
    type: ' Nike Air Max 97',
    price: '500',
    oldPrice: '',
    discount: '',
    currency: 'EGP',
    isFavorite: true,
    isOffer: false,
  ),
  ProductModel(
    title: 'Nike Air Max 97 wiefjklejk lwflkejlkfjwlkem jfwojepofjkwpoek joeifwoijfeiojo jfwiojofjo',
    image: 'https://picsum.photos/id/87/200/300',
    type: ' Nike Air Max 97',
    price: '500',
    oldPrice: '700',
    discount: '50%',
    currency: 'EGP',
    isFavorite: false,
    isOffer: true,
  ),
  ProductModel(
    title: 'Nike Air Max 97 fwejpwkepofkpkepkwpkepf',
    image: 'https://picsum.photos/id/21/200/300',
    type: ' lle;wf 97',
    price: '500',
    oldPrice: '',
    discount: '',
    currency: 'EGP',
    isFavorite: true,
    isOffer: false,
  ),
  ProductModel(
    title: 'Nike Air Max 97 ewefwefw',
    image: 'https://picsum.photos/id/45/200/300',
    type: ' Nike Air Max 97',
    price: '500',
    oldPrice: '700',
    discount: '10%',
    currency: 'EGP',
    isFavorite: false,
    isOffer: true,
  ),
  ProductModel(
    title: 'Nike Air Max 97fwevrehwwwwwwwwwwgbtr',
    image: 'https://picsum.photos/id/29/200/300',
    type: ' Nike Air Max 97',
    price: '500',
    oldPrice: '700',
    discount: '50%',
    currency: 'EGP',
    isFavorite: true,
    isOffer: true,
  ),
  ProductModel(
    title: 'Nike Air Max 97fweffw4twf',
    image: 'https://picsum.photos/id/24/200/300',
    type: ' Nike Air Max 97',
    price: '900',
    oldPrice: '1000',
    discount: '30%',
    currency: 'EGP',
    isFavorite: false,
    isOffer: false,
  ),
  ProductModel(
    title: 'Nike Air Max 97 Black White version fewee wgeeeewf fwfewfef wqfffffffffffffffff fwqefqwfqw fweqf  1',
    image: 'https://picsum.photos/id/3/200/300',
    type: ' Nike Air Max 97',
    price: '500',
    oldPrice: '',
    discount: '',
    currency: 'EGP',
    isFavorite: true,
    isOffer: false,
  ),
  ProductModel(
    title: 'Nike Air Max 97 wiefjklejk lwflkejlkfjwlkem jfwojepofjkwpoek joeifwoijfeiojo jfwiojofjo',
    image: 'https://picsum.photos/id/5/200/300',
    type: ' Nike Air Max 97',
    price: '500',
    oldPrice: '700',
    discount: '50%',
    currency: 'EGP',
    isFavorite: false,
    isOffer: true,
  ),
  ProductModel(
    title: 'Nike Air Max 97 fwejpwkepofkpkepkwpkepf',
    image: 'https://picsum.photos/id/728/200/300',
    type: ' lle;wf 97',
    price: '500',
    oldPrice: '',
    discount: '',
    currency: 'EGP',
    isFavorite: true,
    isOffer: false,
  ),
  ProductModel(
    title: 'Nike Air Max 97 ewefwefw',
    image: 'https://picsum.photos/id/75/200/300',
    type: ' Nike Air Max 97',
    price: '500',
    oldPrice: '700',
    discount: '10%',
    currency: 'EGP',
    isFavorite: false,
    isOffer: true,
  ),
  ProductModel(
    title: 'Nike Air Max 97fwevrehwwwwwwwwwwgbtr',
    image: 'https://picsum.photos/id/24/200/300',
    type: ' Nike Air Max 97',
    price: '500',
    oldPrice: '700',
    discount: '50%',
    currency: 'EGP',
    isFavorite: true,
    isOffer: true,
  ),
  ProductModel(
    title: 'Nike Air Max 97fweffw4twf',
    image: 'https://picsum.photos/id/58/200/300',
    type: ' Nike Air Max 97',
    price: '900',
    oldPrice: '1000',
    discount: '30%',
    currency: 'EGP',
    isFavorite: false,
    isOffer: false,
  ),
  ProductModel(
    title: 'Nike Air Max 97 Black White version fewee wgeeeewf fwfewfef wqfffffffffffffffff fwqefqwfqw fweqf  1',
    image: 'https://picsum.photos/id/553/200/300',
    type: ' Nike Air Max 97',
    price: '500',
    oldPrice: '',
    discount: '',
    currency: 'EGP',
    isFavorite: true,
    isOffer: false,
  ),
  ProductModel(
    title: 'Nike Air Max 97 wiefjklejk lwflkejlkfjwlkem jfwojepofjkwpoek joeifwoijfeiojo jfwiojofjo',
    image: 'https://picsum.photos/id/72/200/300',
    type: ' Nike Air Max 97',
    price: '500',
    oldPrice: '700',
    discount: '50%',
    currency: 'EGP',
    isFavorite: false,
    isOffer: true,
  ),
  ProductModel(
    title: 'Nike Air Max 97 fwejpwkepofkpkepkwpkepf',
    image: 'https://picsum.photos/id/75/200/300',
    type: ' lle;wf 97',
    price: '500',
    oldPrice: '',
    discount: '',
    currency: 'EGP',
    isFavorite: true,
    isOffer: false,
  ),
  ProductModel(
    title: 'Nike Air Max 97 ewefwefw',
    image: 'https://picsum.photos/id/27/200/300',
    type: ' Nike Air Max 97',
    price: '500',
    oldPrice: '700',
    discount: '10%',
    currency: 'EGP',
    isFavorite: false,
    isOffer: true,
  ),
  ProductModel(
    title: 'Nike Air Max 97fwevrehwwwwwwwwwwgbtr',
    image: 'https://picsum.photos/id/68/200/300',
    type: ' Nike Air Max 97',
    price: '500',
    oldPrice: '700',
    discount: '50%',
    currency: 'EGP',
    isFavorite: true,
    isOffer: true,
  ),
  ProductModel(
    title: 'Nike Air Max 97fweffw4twf',
    image: 'https://picsum.photos/id/64/200/300',
    type: ' Nike Air Max 97',
    price: '900',
    oldPrice: '1000',
    discount: '30%',
    currency: 'EGP',
    isFavorite: false,
    isOffer: false,
  ),
];

List<String> typesItems = [
  'Shoses',
  'Closes',
  'Shirts',
  'Pants',
  'Jackets',
  'Accessories',
  'Bags',
  'Hats',
  'Glasses',
  'Belts',
  'Socks',
  'Shoes',
];

String productDec =
    'X SPEEDPORTAL MESSI.1 FIRM GROUNDA speed boot that showcases MESSI style, made in part with recycled materials.Mind. Body. Boot. Connected in a flash. Slip on the adidas X Speedportal to unleash speed in every dimension. The Speedskin upper of this football boot features a montage of Messi-inspired designs, with a flexible adidas PRIMEKNIT collar, carbon heel lock and stability studs for a secure fit at high speeds. Additional forefoot studs on the Speedframe outsole help boost acceleration on firm ground';
